"""extracts tables from PDFs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_ingest.pdftables.ipynb.

# %% auto 0
__all__ = ['ingest_pdf', 'PDFTables']

# %% ../../nbs/01_ingest.pdftables.ipynb 3
import math
import os
import warnings
from pathlib import Path
from typing import List, Optional

try:
    from gmft.auto import AutoTableFormatter, CroppedTable, TableDetector
    from gmft.pdf_bindings import PyPDFium2Document

    DETECTOR = TableDetector()
    FORMATTER = AutoTableFormatter()
    GMFT_INSTALLED = True
except ImportError:
    GMFT_INSTALLED = False


def ingest_pdf(pdf_path):  # produces list[CroppedTable]
    doc = PyPDFium2Document(pdf_path)
    tables = []
    for page in doc:
        tables += DETECTOR.extract(page)
    return tables, doc


class PDFTables:
    def __init__(self, dfs: Optional[List] = None, titles: Optional[List] = None):
        """
        Extracts tables from PDFs
        """
        self.dfs = dfs
        self.titles = titles

    @classmethod
    def from_file(cls, pdf_filename: str, verbose=False):
        """
        Extract tables and their captions.

        **Args**
        
        - pdf_filename: path to PDF file
        - verbose: If True, show progress
        """
        obj = cls()

        if not GMFT_INSTALLED:
            raise ImportError("Please install the gmft package: pip install gmft")

        tables, doc = ingest_pdf(pdf_filename)

        dfs = []
        captions = []
        for table in tables:
            try:
                ft = FORMATTER.extract(table)
                dfs.append(ft.df())
            except Exception as e:
                warnings.warn(f"Failed to extract table: {e}")
                continue

            try:
                tup = table.captions()
                if tup[0].lower().startswith("table"):
                    caption = tup[0]
                elif tup[1].lower().startswith("table"):
                    caption = tup[1]
                else:
                    caption = " ".join(table.captions())
                captions.append(caption)
            except:
                captions.append(None)

        obj.dfs = dfs
        obj.captions = captions
        doc.close()
        return obj

    def table_to_markdown(self, table_df, caption=None):
        """
        Converts pd.Dataframe to markdown
        """
        table_md = "|"
        for col_name, col in table_df.items():
            table_md += f"{col_name}|"
        table_md += "\n|"
        for col_name, col in table_df.items():
            table_md += f"---|"
        table_md += "\n"
        for row in table_df.itertuples():
            table_md += "|"
            for col in row[1:]:
                table_md += f"{col}|"
            table_md += "\n"
        if caption:
            table_summary = (
                f"The following table in markdown format has the caption: {caption}."
            )
        else:
            table_summary = f"The following table in markdown format includes this list of columns:\n"
            for col in table_df.columns:
                table_summary += f"- {col}\n"

        return table_summary + "\n" + table_md

    def get_tables(self, as_markdown=False):
        return self.dfs

    def get_captions(self):
        return self.captions

    def to_markdown(self):
        """
        Convert results to LLM-friendly markdown.
        Returns a list of strings representing the tables.
        """
        results = []
        for i, df in enumerate(self.dfs):
            caption = self.captions[i]
            md = self.table_to_markdown(df, caption=caption)
            results.append(md)
        return results

    def get_markdown_tables(self):
        """
        Returns  list of all tables as Markdown, including captions
        """
        md_tables = []
        for i, df in enumerate(self.dfs):
            caption = self.captions[i]
            md_table = self.table_to_markdown(df, caption)        
            md_tables.append(md_table)
        return md_tables



