[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "onprem"
dynamic = ["version"]
description = "A tool for running on-premises large language models on non-public data"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{name = "Arun S. Maiya", email = "arun@maiya.net"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = ['requests', 'tqdm', 'charset_normalizer', 'pyparsing', 'pandas', 'whoosh-reloaded', 'litellm', 'huggingface_hub', 'langchain', 'langchain-core', 'langchain-text-splitters', 'langchain_litellm', 'langchain-openai']

[project.urls]
Repository = "https://github.com/amaiya/onprem"
Documentation = "https://amaiya.github.io/onprem"

[project.entry-points.nbdev]
onprem = "onprem._modidx:d"

[project.optional-dependencies]
dev = ['nbdev', 'onprem[all]']
chroma = ['langchain_chroma', 'chromadb']
elasticsearch = ['elasticsearch']
sharepoint = ['requests_ntlm']
explain = ['shap', 'matplotlib']
chinese = ['jieba']
aws = ['boto3']
agent = ['patchpal>=0.25.0']
guidance = ['guidance>=0.1.5']
huggingface = ['transformers', 'accelerate', 'sentence_transformers', 'setfit', 'langchain-huggingface']
docs = ['unstructured', 'PyMuPDF', 'pymupdf4llm==0.0.17', 'extract-msg', 'tabulate', 'pandoc', 'pypandoc', 'nltk>=3.9.1', 'syntok', 'python-magic', 'openpyxl', 'langdetect']
docs-ml = ['unstructured[all-docs]', 'gmft']
app = ['streamlit']
sklearn = ['scikit-learn']
all = ['langchain_chroma', 'chromadb', 'elasticsearch', 'requests_ntlm', 'shap', 'matplotlib', 'jieba', 'boto3', 'patchpal>=0.25.0', 'guidance>=0.1.5', 'transformers', 'accelerate', 'sentence_transformers', 'setfit', 'langchain-huggingface', 'unstructured[all-docs]', 'gmft', 'PyMuPDF', 'pymupdf4llm==0.0.17', 'extract-msg', 'tabulate', 'pandoc', 'pypandoc', 'nltk>=3.9.1', 'syntok', 'python-magic', 'openpyxl', 'langdetect', 'streamlit', 'scikit-learn']


[project.scripts]
onprem = "onprem.app.console:cli"

[tool.setuptools.dynamic]
version = {attr = "onprem.__version__"}

[tool.setuptools.packages.find]
include = ["onprem*"]

[tool.setuptools.package-data]
onprem = [
    "app/.streamlit/*.toml",
    "app/static/*",
    "app/pages/*.py"
]

[tool.nbdev]
branch = 'master'
custom_sidebar = true


# Notes:
# pinning to ChromaDB due to backwards compatibility issues
# pinning: pymupdf4llm==0.0.17 because later versions produce lower-quality outputs based on tests
# downloads: nltk punkt/averaged_perceptron_tagger (required by utils.extract_noun_phrases)
# downloads: models for infer_table_structure and ocr (required by load_single_document)
