FROM python:3.10
RUN python3 -m pip install --upgrade pip wheel setuptools
RUN python3 -m pip install torch torchvision torchaudio \
  --index-url https://download.pytorch.org/whl/cpu
RUN python3 -m pip install llama-cpp-python streamlit
COPY . .
RUN python3 -m pip install .
CMD python3